import './globals.css';
import type { Metadata } from 'next';
import { Jost } from 'next/font/google';
import Provider from './ThemeProvider';
import MainLayout from '@/src/components/MainLayout';

const jost = Jost({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'CatsCatsCats',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${jost.className} bg-lightgray text-black dark:bg-black dark:text-white`}
      >
        <Provider>
          <MainLayout>{children}</MainLayout>
        </Provider>
      </body>
    </html>
  );
}
